/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea2_login;

import java.awt.Color;

/**
 *
 * @author elian
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        PasswordF = new javax.swing.JPasswordField();
        Iniciar = new javax.swing.JPanel();
        inSesion = new javax.swing.JLabel();
        limite = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo usac (1) (1).png"))); // NOI18N
        Fondo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 80));

        contraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(102, 102, 102));
        contraseña.setText("Contraseña");
        Fondo.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 90, 30));

        texto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        texto.setForeground(new java.awt.Color(153, 153, 153));
        texto.setText("Ingrese a su cuenta");
        Fondo.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 40));

        usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(102, 102, 102));
        usuario.setText("Usuario");
        Fondo.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 60, 30));
        Fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 270, 20));
        Fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 270, 20));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        Fondo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 270, 40));

        PasswordF.setBackground(new java.awt.Color(255, 255, 255));
        PasswordF.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        PasswordF.setForeground(new java.awt.Color(51, 51, 51));
        PasswordF.setBorder(null);
        Fondo.add(PasswordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 260, 40));

        Iniciar.setBackground(new java.awt.Color(51, 102, 255));
        Iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarMouseEntered(evt);
            }
        });

        inSesion.setBackground(new java.awt.Color(255, 255, 255));
        inSesion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        inSesion.setForeground(new java.awt.Color(255, 255, 255));
        inSesion.setText("                           Iniciar sesión");
        inSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inSesionMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout IniciarLayout = new javax.swing.GroupLayout(Iniciar);
        Iniciar.setLayout(IniciarLayout);
        IniciarLayout.setHorizontalGroup(
            IniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IniciarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        IniciarLayout.setVerticalGroup(
            IniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IniciarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inSesion.getAccessibleContext().setAccessibleName("Iniciar sesión");

        Fondo.add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 230, 30));

        limite.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout limiteLayout = new javax.swing.GroupLayout(limite);
        limite.setLayout(limiteLayout);
        limiteLayout.setHorizontalGroup(
            limiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        limiteLayout.setVerticalGroup(
            limiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        Fondo.add(limite, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void inSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inSesionMouseEntered
       
    }//GEN-LAST:event_inSesionMouseEntered

    private void IniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseEntered
       
    }//GEN-LAST:event_IniciarMouseEntered

    private void inSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inSesionMouseClicked
       
        String Usuario= "Elian Angel";
        String password= "202044192";
        
        String pass= new String(PasswordF.getPassword());
        
        if(txtUsuario.getText().equals(Usuario) && pass.equals(password))
        {
            Informacion inf= new Informacion();
            inf.setVisible(true);
            this.setVisible(false);
            
        }
        else
        {
            Error error= new Error();
            error.setVisible(true);
        }
        
    }//GEN-LAST:event_inSesionMouseClicked

    
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Iniciar;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField PasswordF;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel inSesion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel limite;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
